name: 'Create Pull Request'
description: 'This action creates and attemps to automatically merge pull requests'
inputs:
  title:
    description: Title of the pull request
    required: true
  repo:
    default: ${{ github.repository }}
  head:
    default: ${{ github.ref }}
  base:
    required: true
  automerge:
    default: true
  token:
    required: true
outputs:
  number:
    description: Number of the pull request.
  url:
    description: Url of the pull  request.
runs:
  using: 'node16'
  main: 'dist/index.js'
