name: 'Create Pull Request'
description: 'This action creates and attemps to automatically merge pull requests'
inputs:
  title:
    description: Title of the pull request
    required: true
  repo:
    description: Repository name with owner. (owner/repo)
    default: ${{ github.event.repository.parent.full_name }}
  head:
    description: Head branch to merge.
    default: "${{ github.repository_owner }}:${{ github.ref_name }}"
  base:
    description: Base branch to merge into.
    default: ${{ github.event.repository.parent.default_branch }}
  automerge:
    description: True if the pull request should be mergd automatically.
    default: true
  token:
    description: GitHub access token.
    required: true
outputs:
  number:
    description: Number of the pull request.
  url:
    description: Url of the pull  request.
runs:
  using: 'node16'
  main: 'dist/index.js'
